Repository ad-earth/FE-client, pull requests merged in 2022-11, with the labels that each got.

#184 api instance 수정 및 라우팅 변경
  src/components/card/Card.tsx
  src/components/detailPage/buttons/Buttons.tsx
  src/components/listPage/cardIcon/CardIcon.tsx
  src/shared/apis/api.ts
Labels: 상세페이지

#187 🐛 fix. 임시 주석처리
  src/components/paymentPage/pdtInfo/PdtInfo.tsx
Labels: 결제페이지

#188 🐛 fix. 쿼리 요청 불안정으로 인한 주석처리
  src/components/listPage/cardIcon/CardIcon.tsx
  src/containers/listPage/listModal/ListModal.tsx
Labels: 장보기페이지, 검색페이지

#183 마이페이지 버그 수정 및 코드 추가
  src/components/myPage/asideNav/asideNav.style.ts
  src/components/myPage/order/orderList/OrderList.tsx
  src/components/myPage/order/orderListDetail/OrderListDetail.tsx
  src/components/myPage/order/orderListDetail/orderListDetail.style.ts
  src/components/myPage/order/orderListDetail/orderListDetail.type.ts
  src/containers/myPage/orderDetail/OrderDetail.tsx
  src/containers/myPage/orderDetail/orderDetail.type.ts
  src/pages/MyPage.tsx
Labels: 마이페이지

#189 11/4 수정사항
  src/components/detailPage/buttons/Buttons.tsx
  src/components/detailPage/buttons/useOptionList.ts
  src/components/detailPage/productOptions/ProductOptions.tsx
  src/components/detailPage/productOptions/optionHandler.ts
  src/hooks/useViewport.ts
  src/shared/types/types.ts
  src/shared/utils/putCartDB.ts
  src/shared/utils/putPaymentDB.ts
Labels: 상세페이지

#190 11/5 IDB 할인가 미적용 버그 수정
  src/components/detailPage/buttons/Buttons.tsx
  src/components/detailPage/buttons/buttons.type.ts
  src/components/detailPage/buttons/useOptionList.ts
  src/components/detailPage/productOptions/optionHandler.ts
  src/components/detailPage/productQty/ProductQty.tsx
  src/components/detailPage/productQty/useTotalOptionPrice.ts
  src/components/detailPage/productQty/useTotalOptionQty.ts
  src/components/detailPage/productQty/useTotalPrice.ts
  src/components/detailPage/productQty/useTotalQty.ts
  src/shared/utils/putCartDB.ts
  src/shared/utils/putPaymentDB.ts
Labels: bug, 상세페이지

#191 결제페이지 디비 삭제 기능 & 검색/리스트 페이지 카드 모달 쿼리 요청
  src/App.tsx
  src/components/card/Card.tsx
  src/components/detailPage/buttons/Buttons.tsx
  src/components/listPage/cardBadge/CardBadge.tsx
  src/components/listPage/cardIcon/CardIcon.tsx
  src/components/listPage/cardIcon/useCardIconQuery.ts
  src/components/listPage/catDrop/CateDrop.tsx
  src/components/listPage/cateButton/CateButton.tsx
  src/components/listPage/pagination/PageBtn.tsx
  src/components/paymentPage/newPayInput/NewPayInput.tsx
  src/components/paymentPage/payAgree/PayAgree.tsx
  src/components/paymentPage/payMethod/PayMethod.tsx
  src/components/paymentPage/payMethodInput/PayMethodInput.tsx
  src/components/paymentPage/payMethodInput/payMethodInput.style.ts
  src/components/paymentPage/payRadioBtn/PayRadioBtn.tsx
  src/components/paymentPage/payRadioBtn/payRadioBtn.style.ts
  src/components/paymentPage/payRadioBtn/payRadioBtn.type.ts
  src/components/paymentPage/paySummary/PaySummary.tsx
  src/components/paymentPage/payTitle/PayTitle.tsx
  src/components/paymentPage/payUserInfo/PayUserInfo.tsx
  src/components/paymentPage/payUserInput/PayUserInput.tsx
  src/components/paymentPage/pdtInfo/PdtInfo.tsx
  src/components/paymentPage/pdtInfo/pdInfo.type.ts
  src/containers/completePage/completeBody/CompleteBody.tsx
  src/containers/completePage/completeBody/useCompleteBodyQuery.ts
  src/containers/listPage/cardList/CardList.tsx
  src/containers/listPage/cardList/useCardListQuery.ts
  src/containers/listPage/listModal/ListModal.tsx
  src/containers/paymentPage/orderPList/OrderPList.tsx
  src/containers/paymentPage/orderPList/useOrderPListQuery.ts
  src/containers/searchPage/searchBody/SearchBody.tsx
  src/containers/searchPage/searchBody/useSearchBodyQuery.ts
  src/elements/buttons/Buttons.tsx
  src/elements/loading/Loading.tsx
  src/hooks/useDeletePayDB.ts
  src/pages/CompletePage.tsx
  src/pages/ListPage.tsx
  src/pages/PaymentPage.tsx
  src/pages/SearchPage.tsx
  src/redux/reducer/payCheckSlice.ts
Labels: refactoring, 장보기페이지, 결제페이지, 검색페이지

#193 fix. 리스트 모달 수정
  src/components/detailPage/buttons/Buttons.tsx
  src/components/listPage/cardIcon/CardIcon.tsx
  src/components/listPage/catDrop/CateDrop.tsx
  src/components/listPage/cateButton/cateButton.style.ts
  src/components/modal/listModal/ListModal.tsx
  src/components/modal/listModal/listModal.style.ts
  src/containers/detailPage/details/useGetDetailQuery.ts
  src/containers/listPage/cardList/CardList.tsx
  src/containers/listPage/listModal/ListModal.tsx
  src/containers/listPage/listModal/listModal.style.ts
  src/redux/reducer/listSlice.ts
Labels: 장보기페이지

#194 11/12 옵션 버그 수정
  src/components/detailPage/productOptions/ProductOptions.tsx
Labels: bug

#195 Dam
  src/components/cartPage/ItemList.tsx
  src/components/cartPage/itemList.type.ts
  src/components/detailPage/productQty/ProductQty.tsx
  src/components/header/aside/AsideHeader.tsx
  src/components/header/aside/asideHeader.style.ts
  src/components/header/aside/asideHeader.type.ts
  src/components/header/scroll/ScrollHeader.tsx
  src/components/header/scroll/scrollHeader.style.ts
  src/components/modal/optionModal/OptionModal.tsx
  src/components/modal/optionModal/cartButtons/CartButtons.tsx
  src/components/modal/optionModal/cartButtons/cartButtons.style.ts
  src/components/modal/optionModal/optionModal.style.ts
  src/components/modal/optionModal/optionModal.type.ts
  src/components/modal/optionModal/useGetOption.ts
  src/components/modal/schProdModal/SchProdModal.tsx
  src/components/modal/schProdModal/schProdModal.style.ts
  src/components/modal/schProdModal/schProdModal.type.ts
  src/components/modal/searchModal/schForm/searchForm.style.ts
  src/components/modal/searchModal/schForm/searchId/SearchId.tsx
  src/components/modal/searchModal/schForm/searchId/searchId.type.ts
  src/components/modal/searchModal/schForm/serchPass/SearchPass.tsx
  src/components/modal/searchModal/schForm/serchPass/searchPass.type.ts
  src/components/modal/searchModal/schModal/SearchModal.tsx
  src/components/modal/searchModal/schModal/searchModal.style.ts
  src/components/modal/searchModal/schModal/searchModal.type.ts
  src/components/modal/userInfoModal/UserInfoModal.tsx
  src/components/modal/userInfoModal/userInfoModal.style.ts
  src/components/modal/userInfoModal/userInfoModal.type.ts
  src/components/signUpPage/addressForm/AddressForm.tsx
  src/components/signUpPage/addressForm/addressForm.style.ts
  src/components/signUpPage/addressForm/addressForm.type.ts
  src/components/signUpPage/profile/Profile.tsx
  src/components/signUpPage/profile/profile.style.ts
  src/components/signUpPage/profile/profile.type.ts
  src/containers/cartPage/cartList/CartList.tsx
  src/containers/cartPage/cartList/cartList.style.ts
  src/containers/cartPage/cartReceipt/CartReceipt.tsx
  src/containers/cartPage/cartReceipt/cartReceipt.style.ts
  src/containers/footer/Footer.tsx
  src/containers/footer/footer.style.ts
  src/containers/header/Header.tsx
  src/containers/header/header.style.ts
  src/containers/loginPage/LoginForm.tsx
  src/containers/loginPage/loginForm.style.ts
  src/containers/loginPage/loginForm.type.ts
  src/containers/loginPage/useLoginForm.ts
  src/containers/signupPage/SignUpForm.tsx
  src/containers/signupPage/signUpForm.type.ts
  src/containers/signupPage/useSignUpForm.ts
  src/hooks/useAllCartDB.ts
  src/redux/reducer/cartSlice.ts
  src/redux/reducer/optionSlice.ts
  src/redux/store.ts
  src/shared/types/types.ts
  src/shared/utils/delCartDB.ts
  src/shared/utils/putCartDB.ts
  src/shared/utils/putPaymentDB.ts
Labels: refactoring

#197 리스트 모달 겹침 해결
  src/assets/icons/message-circle.svg
  src/components/card/Card.tsx
  src/components/listPage/cardIcon/CardIcon.tsx
  src/components/listPage/cardIcon/cardIcon.style.ts
  src/components/listPage/pagination/PageBtn.tsx
  src/components/listPage/pagination/pageBtn.sytle.ts
  src/components/modal/listModal/listModal.style.ts
  src/components/paymentPage/pdtInfo/PdtInfo.tsx
  src/containers/paymentPage/orderPList/OrderPList.tsx
Labels: 장보기페이지, 결제완료페이지

#198 11/17 메인 버튼 코드 추가 & 옵션 드롭다운 버그 수정
  src/components/detailPage/buttons/Buttons.tsx
  src/components/detailPage/productOptions/ProductOptions.tsx
Labels: bug, 상세페이지
