Repository ad-earth/FE-client, pull requests merged in 2022-09, with the labels that each got.

#49 상세페이지 view 구현
  src/components/detailPage/Comment.tsx
  src/components/detailPage/CommentList.tsx
  src/components/detailPage/DeliveryInfo.tsx
  src/components/detailPage/ProdComments.tsx
  src/components/detailPage/ProdDetails.tsx
  src/components/detailPage/ProdOpt.tsx
  src/components/modal/reaviewModal/ReviewModal.tsx
  src/containers/detailPage/ProdContents.tsx
  src/pages/DetailPage.tsx
Labels: task

#52 마이페이지 화면 구현 , 공통 컴포넌트 수정
  src/App.tsx
  src/components/modal/Modal.tsx
  src/components/modal/reaviewModal/ReviewModal.tsx
  src/components/modal/reaviewModal/ReviewModalStyle.ts
  src/components/modal/withdrawalModal/WithdrawalModal.tsx
  src/components/myPage/AsideNav.tsx
  src/components/myPage/OderList.tsx
  src/components/myPage/WishCard.tsx
  src/components/myPage/order/OderList.tsx
  src/components/myPage/order/OrderAddress.tsx
  src/components/myPage/order/OrderAmount.tsx
  src/components/myPage/order/OrderListDetail.tsx
  src/components/myPage/order/OrderNumber.tsx
  src/components/myPage/order/OrderNumerDetail.tsx
  src/components/myPage/order/OrderUserInfo.tsx
  src/components/myPage/order/Product.tsx
  src/containers/myPage/Cancel.tsx
  src/containers/myPage/Order.tsx
  src/containers/myPage/OrderDetail.tsx
  src/containers/myPage/Wish.tsx
Labels: invalid, task

#54 결제 페이지 View 작업
  src/components/paymentPage/OrderPdtInfo.tsx
  src/components/paymentPage/PayAgree.tsx
  src/components/paymentPage/PayMethod.tsx
  src/components/paymentPage/PayRadioBtn.tsx
  src/components/paymentPage/PaySummary.tsx
  src/components/paymentPage/PayTitle.tsx
  src/components/paymentPage/PayUserInfo.tsx
  src/components/paymentPage/PdtInfo.tsx
  src/containers/paymentPage/OrderPList.tsx
  src/containers/paymentPage/OrderPay.tsx
  src/pages/PaymentPage.tsx
Labels: task

#61 카트 모달 추가
  src/components/listPage/CardIcon.tsx
  src/containers/listPage/ListModal.tsx
  src/pages/ListPage.tsx
Labels: task

#60 마이페이지 화면 구현
  package.json
  src/App.tsx
  src/components/Card.tsx
  src/components/myPage/AsideNav.tsx
  src/components/myPage/UserHeadInfo.tsx
  src/components/myPage/WishCard.tsx
  src/components/myPage/cancel/CancelAmount.tsx
  src/components/myPage/cancel/CancelInfo.tsx
  src/components/myPage/cancel/CancelListDetail.tsx
  src/components/myPage/order/OderList.tsx
  src/components/myPage/order/OrderAmount.tsx
  src/components/myPage/order/OrderNumber.tsx
  src/components/myPage/order/Product.tsx
  src/containers/listPage/CardList.tsx
  src/containers/myPage/Aside.tsx
  src/containers/myPage/Cancel.tsx
  src/containers/myPage/CancelDetail.tsx
  src/containers/myPage/Order.tsx
  src/containers/myPage/UserHead.tsx
  src/containers/myPage/Wish.tsx
  src/hook/useMobileMediaQuery.ts
  src/pages/MyPage.tsx
  yarn.lock
Labels: task

#62 상세페이지 상단 링크 추가
  src/components/detailPage/Comment.tsx
  src/components/detailPage/CommentList.tsx
  src/components/detailPage/DeliveryInfo.tsx
  src/components/detailPage/History.tsx
  src/components/detailPage/ProdCarousel.tsx
  src/components/detailPage/ProdDesc.tsx
  src/components/detailPage/ProdName.tsx
  src/components/detailPage/ProdOpt.tsx
  src/components/mainPage/BestCards.tsx
  src/components/mainPage/MissionBox.tsx
  src/containers/ProdInfo.tsx
  src/containers/detailPage/ProdContents.tsx
  src/containers/mainPage/BestProdList.tsx
  src/containers/mainPage/Jisok.tsx
  src/containers/mainPage/Mission.tsx
  src/containers/mainPage/NewProdList.tsx
  src/containers/mainPage/SocialLinkList.tsx
  src/elements/Badge.tsx
  src/elements/Buttons.tsx
  src/elements/ColorIcons.tsx
  src/elements/Input.tsx
  src/elements/SearchBar.tsx
  src/pages/DetailPage.tsx
  src/style/theme.ts
Labels: task

#65 Feat cartpage
  src/components/Card.tsx
  src/components/cartPage/CartItem.tsx
  src/components/cartPage/CartItemStyle.ts
  src/components/cartPage/ItemList.tsx
  src/components/listPage/CardIcon.tsx
  src/components/listPage/CateButton.tsx
  src/components/modal/optionModal/OptionModal.tsx
  src/components/modal/optionModal/OptionModalStyle.ts
  src/components/modal/reviewModal/ReviewModalStyle.ts
  src/components/modal/searchModal/IdSearch.tsx
  src/components/modal/searchModal/PassSearch.tsx
  src/components/modal/searchModal/SearchModal.tsx
  src/components/modal/searchModal/SearchModalStyle.ts
  src/components/myPage/WishCard.tsx
  src/components/myPage/cancel/CancelAmount.tsx
  src/components/myPage/cancel/CancelInfo.tsx
  src/components/myPage/order/OrderAddress.tsx
  src/components/myPage/order/OrderAmount.tsx
  src/components/myPage/order/OrderListDetail.tsx
  src/components/myPage/order/OrderNumber.tsx
  src/components/myPage/order/OrderUserInfo.tsx
  src/containers/Footer.tsx
  src/containers/cartPage/CartList.tsx
  src/containers/cartPage/CartReceipt.tsx
  src/containers/header/HeaderStyle.ts
  src/containers/myPage/CancelDetail.tsx
  src/elements/Badge.tsx
  src/elements/Input.tsx
  src/elements/SqSearchBar.tsx
  src/pages/CartPage.tsx
  src/pages/LogInPage.tsx
  src/style/theme.ts
Labels: attention!, task

#66 결제페이지 주문자정보 배송지변경 css 추가
  src/components/listPage/CateButton.tsx
  src/components/paymentPage/NewPayInput.tsx
  src/components/paymentPage/PayMethod.tsx
  src/components/paymentPage/PayMethodInput.tsx
  src/components/paymentPage/PayRadioBtn.tsx
  src/components/paymentPage/PayUserInfo.tsx
  src/components/paymentPage/PayUserInput.tsx
  src/components/paymentPage/PdtInfo.tsx
  src/containers/listPage/ListModal.tsx
  src/containers/paymentPage/OrderPList.tsx
  src/elements/Input.tsx
  src/elements/SqSearchBar.tsx
  src/pages/ListPage.tsx
  src/pages/SignUpPage.tsx
Labels: task

#67 결제페이지 반응형 추가 및 theme 변경
  src/containers/paymentPage/OrderPList.tsx
  src/containers/paymentPage/OrderPay.tsx
  src/pages/PaymentPage.tsx
Labels: task

#70 theme 스타일 적용 , 반응형 뷰
  src/App.tsx
  src/components/modal/Modal.tsx
  src/components/modal/reviewModal/ReviewModal.tsx
  src/components/modal/reviewModal/ReviewModalStyle.ts
  src/components/modal/withdrawalModal/WithdrawalModal.tsx
  src/components/modal/withdrawalModal/WithdrawalModalStyle.ts
  src/components/myPage/AsideNav.tsx
  src/components/myPage/UserHeadInfo.tsx
  src/components/myPage/WishCard.tsx
  src/components/myPage/cancel/CancelAmount.tsx
  src/components/myPage/cancel/CancelInfo.tsx
  src/components/myPage/cancel/CancelListDetail.tsx
  src/components/myPage/order/OderList.tsx
  src/components/myPage/order/OrderAddress.tsx
  src/components/myPage/order/OrderAmount.tsx
  src/components/myPage/order/OrderListDetail.tsx
  src/components/myPage/order/OrderNumber.tsx
  src/components/myPage/order/OrderNumerDetail.tsx
  src/components/myPage/order/OrderPaymentMethod.tsx
  src/components/myPage/order/OrderUserInfo.tsx
  src/components/myPage/order/Product.tsx
  src/containers/myPage/Aside.tsx
  src/containers/myPage/Cancel.tsx
  src/containers/myPage/CancelDetail.tsx
  src/containers/myPage/Order.tsx
  src/containers/myPage/OrderDetail.tsx
  src/containers/myPage/UserHead.tsx
  src/containers/myPage/Wish.tsx
  src/pages/MyPage.tsx
Labels: task

#72 리스트 모달 반응형 및 theme 변경
  src/containers/listPage/ListModal.tsx
Labels: task

#73 Feat cartpage
  package.json
  src/App.tsx
  src/components/header/aside/AsideHeader.style.ts
  src/components/header/aside/AsideHeader.tsx
  src/components/header/scroll/ScrollHeader.style.ts
  src/components/header/scroll/ScrollHeader.tsx
  src/components/header/scroll/useScrollHeader.ts
  src/components/modal/optionModal/OptionModal.style.ts
  src/components/modal/optionModal/OptionModal.tsx
  src/components/modal/schProdModal/SchProdModal.style.ts
  src/components/modal/schProdModal/SchProdModal.tsx
  src/components/modal/searchModal/IdSearch.tsx
  src/components/modal/searchModal/PassSearch.tsx
  src/components/modal/searchModal/schForm/SearchForm.style.ts
  src/components/modal/searchModal/schForm/SearchForm.tsx
  src/components/modal/searchModal/schModal/SearchModal.style.ts
  src/components/modal/searchModal/schModal/SearchModal.tsx
  src/components/signUpPage/addressForm/AddressForm.style.ts
  src/components/signUpPage/addressForm/AddressForm.tsx
  src/components/signUpPage/profile/Profile.style.ts
  src/components/signUpPage/profile/Profile.tsx
  src/components/signUpPage/signUpForm/SignUpForm.style.ts
  src/components/signUpPage/signUpForm/SignUpForm.tsx
  src/containers/Footer.tsx
  src/containers/footer/Footer.style.ts
  src/containers/footer/Footer.tsx
  src/containers/header/Header.style.ts
  src/containers/header/Header.tsx
  src/containers/header/HeaderStyle.ts
  src/containers/loginPage/LoginForm.style.ts
  src/containers/loginPage/LoginForm.tsx
  src/containers/myPage/Order.tsx
  src/elements/SearchBar.tsx
  src/hooks/useMobileMediaQuery.ts
  src/pages/LogInPage.tsx
  src/pages/SignUpPage.tsx
  src/shared/apis/api.ts
  src/shared/auth/auth.service.ts
  src/shared/types/types.ts
  src/shared/utils/checkPattern.ts
  src/style/theme.ts
  yarn.lock
Labels: task

#90 mainpage mock api test
  src/App.tsx
  src/components/card/Card.tsx
  src/components/mainPage/bestCards/BestCards.tsx
  src/components/mainPage/newCarousel/NewCarousel.tsx
  src/components/myPage/WishCard.tsx
  src/containers/listPage/cardList/CardList.tsx
  src/containers/searchPage/searchBody/SearchBody.tsx
  src/shared/apis/api.ts
Labels: task

#92 mainpage best products types & custom query hook
  src/App.tsx
  src/components/mainPage/bestCards/BestCards.tsx
  src/components/mainPage/bestCards/bestCards.type.ts
  src/components/mainPage/bestCards/useBestCards.ts
  src/components/mainPage/newCarousel/ useNewCarousel.ts
  src/components/mainPage/newCarousel/NewCarousel.tsx
  src/components/mainPage/newCarousel/newCarousel.type.ts
Labels: attention!, task

#93 공통 타입 및 global fetching indicator 적용
  package.json
  src/App.tsx
  src/components/mainPage/bestCards/BestCards.tsx
  src/components/mainPage/bestCards/bestCards.type.ts
  src/components/mainPage/bestCards/useBestCards.ts
  src/components/mainPage/newCarousel/NewCarousel.tsx
  src/components/mainPage/newCarousel/newCarousel.type.ts
  src/components/mainPage/newCarousel/useNewCarousel.ts
  src/elements/Loading.tsx
  src/shared/types/types.ts
  yarn.lock
Labels: attention!

#94 카드 컴포넌트 이미지 호버 추가 및 기능 개발
  src/components/card/Card.tsx
  src/components/card/card.type.ts
  src/components/listPage/cardBadge/CardBadge.tsx
  src/components/listPage/cardBadge/CardBaged.style.ts
  src/components/listPage/cardBadge/cardBadge.type.ts
  src/components/listPage/cardIcon/CardIcon.tsx
  src/components/listPage/cardIcon/cardIcon.type.ts
  src/containers/listPage/ListModal.tsx
  src/containers/listPage/cardList/CardList.tsx
  src/containers/listPage/cardList/useCardList.ts
  src/containers/searchPage/searchBody/SearchBody.tsx
  src/containers/searchPage/searchBody/useSearchBody.ts
  src/elements/ColorIcons.tsx
  src/shared/apis/api.ts
Labels: task

#96 test branch CICD test
  .github/workflows/main.yml
Labels: attention!

#97 🐛 fix. git action branch 수정
  .github/workflows/main.yml
Labels: attention!

#98 🐛 fix. git action type 변경
  .github/workflows/main.yml
Labels: attention!

#102 📝 feat. 카드 컴포 에러 해결
  src/components/card/Card.style.ts
  src/components/card/card.type.ts
  src/components/listPage/cardIcon/CardIcon.tsx
  src/components/listPage/cardIcon/Cardicon.style.ts
  src/components/mainPage/bestCards/BestCards.tsx
  src/components/mainPage/newCarousel/NewCarousel.tsx
  src/components/myPage/wishCard/WishCard.tsx
  src/containers/listPage/cardList/CardList.style.ts
Labels: task

#104 card compo styl.ts 파일 삭제 및 추가
  src/components/card/card.style.ts
  src/components/listPage/cardIcon/cardIcon.style.ts
  src/containers/listPage/cardList/cardList.style.ts
Labels: task

#103 에러 수정
  .github/workflows/main.yml
  src/components/card/card.style.ts
  src/components/card/card.type.ts
  src/components/listPage/cardIcon/CardIcon.tsx
  src/components/listPage/cardIcon/cardIcon.style.ts
  src/components/mainPage/bestCards/BestCards.tsx
  src/components/mainPage/newCarousel/NewCarousel.tsx
  src/components/myPage/wishCard/WishCard.tsx
  src/containers/listPage/cardList/cardList.style.ts
Labels: task

#108 마이페이지 기능구현
  package.json
  src/App.test.tsx
  src/App.tsx
  src/components/modal/reviewModal/ReviewModal.tsx
  src/components/modal/reviewModal/reviewModal.style.ts
  src/components/modal/reviewModal/useReviewModal.ts
  src/components/modal/withdrawalModal/WithdrawalModal.tsx
  src/components/modal/withdrawalModal/useWithdrawalModal.ts
  src/components/myPage/asideNav/AsideNav.tsx
  src/components/myPage/asideNav/asideNav.style.ts
  src/components/myPage/cancel/cancelAmount/CancelAmount.tsx
  src/components/myPage/cancel/cancelAmount/cancelAmount.style.ts
  src/components/myPage/cancel/cancelInfo/CancelInfo.tsx
  src/components/myPage/cancel/cancelInfo/cancelInfo.style.ts
  src/components/myPage/cancel/cancelListDetail/CancelListDetail.tsx
  src/components/myPage/order/Product.tsx
  src/components/myPage/order/orderAddress/OrderAddress.tsx
  src/components/myPage/order/orderAmount/OrderAmount.tsx
  src/components/myPage/order/orderList/OrderList.tsx
  src/components/myPage/order/orderListDetail/OrderListDetail.tsx
  src/components/myPage/order/orderNumber/OrderNumber.tsx
  src/components/myPage/order/orderNumerDetail/OrderNumerDetail.tsx
  src/components/myPage/order/orderUserInfo/OrderUserInfo.tsx
  src/components/myPage/order/product/Product.tsx
  src/components/myPage/order/product/product.style.ts
  src/components/myPage/userHeadInfo/UserHeadInfo.tsx
  src/components/myPage/wishCard/WishCard.tsx
  src/containers/myPage/Cancel.tsx
  src/containers/myPage/Order.tsx
  src/containers/myPage/OrderDetail.tsx
  src/containers/myPage/cancel/Cancel.tsx
  src/containers/myPage/cancel/cancel.style.ts
  src/containers/myPage/cancel/cancel.type.ts
  src/containers/myPage/cancel/useCancel.tsx
  src/containers/myPage/cancelDetail/CancelDetail.tsx
  src/containers/myPage/cancelDetail/cancelDetail.style.ts
  src/containers/myPage/cancelDetail/useCancelDetail.ts
  src/containers/myPage/order/Order.tsx
  src/containers/myPage/order/order.style.ts
  src/containers/myPage/order/order.type.ts
  src/containers/myPage/order/useOrder.ts
  src/containers/myPage/orderDetail/OrderDetail.tsx
  src/containers/myPage/orderDetail/orderDetail.style.ts
  src/containers/myPage/orderDetail/orderDetail.type.ts
  src/containers/myPage/orderDetail/useOrderDetail.ts
  src/containers/myPage/wish/Wish.tsx
  src/containers/myPage/wish/useWish.ts
  src/containers/myPage/wish/wish.type.ts
  src/pages/MyPage.tsx
  src/shared/apis/api.ts
  tsconfig.json
  yarn.lock
Labels: task

#109 feat. 장보기 페이지, 검색 페이지 기능 추가
  src/components/card/Card.tsx
  src/components/card/card.style.ts
  src/components/card/card.type.ts
  src/components/listPage/cardBadge/CardBadge.tsx
  src/components/listPage/cardBadge/cardBadge.type.ts
  src/components/listPage/cardIcon/CardIcon.tsx
  src/components/listPage/cardIcon/cardIcon.style.ts
  src/components/listPage/cardIcon/cardIcon.type.ts
  src/components/listPage/pagination/PageBtn.tsx
  src/components/listPage/pagination/pageBtn.sytle.ts
  src/components/searchPage/sPageBtn/SPageBtn.tsx
  src/components/searchPage/searchCateDrop/SearchCateDrop.tsx
  src/components/searchPage/sqSearchBar/SqSearchBar.tsx
  src/components/searchPage/sqSearchBar/sqSearchBar.style.ts
  src/containers/listPage/cardList/CardList.tsx
  src/containers/listPage/cardList/cardList.type.ts
  src/containers/listPage/cardList/useCardList.ts
  src/containers/searchPage/searchBody/SearchBody.tsx
  src/containers/searchPage/searchBody/searchPage.type.ts
  src/containers/searchPage/searchBody/useSearchBody.ts
  src/pages/ListPage.tsx
  src/pages/SearchPage.tsx
  src/shared/apis/api.ts
Labels: task

#111 상세페이지 옵션 및 가격 UI 작업
  src/components/detailPage/history/History.tsx
  src/components/detailPage/prodBtns/ProdBtns.tsx
  src/components/detailPage/prodBtns/prodBtns.style.ts
  src/components/detailPage/prodBtns/prodBtns.type.ts
  src/components/detailPage/prodCarousel/ProdCarousel.tsx
  src/components/detailPage/prodCarousel/prodCarousel.style.ts
  src/components/detailPage/prodCnt/ProdCnt.tsx
  src/components/detailPage/prodCnt/prodCnt.style.ts
  src/components/detailPage/prodCnt/prodCnt.type.ts
  src/components/detailPage/prodDesc/ProdDesc.tsx
  src/components/detailPage/prodDesc/prodDesc.type.ts
  src/components/detailPage/prodImg/ProdImg.tsx
  src/components/detailPage/prodImg/prodImg.style.ts
  src/components/detailPage/prodImg/prodImg.type.ts
  src/components/detailPage/prodName/ProdName.tsx
  src/components/detailPage/prodName/prodName.style.ts
  src/components/detailPage/prodName/prodName.type.ts
  src/components/detailPage/prodOpt/ProdOpt.tsx
  src/components/detailPage/prodOpt/prodOpt.style.ts
  src/components/detailPage/prodOpt/prodOpt.type.ts
  src/containers/detailPage/prodInfo/ProdInfo.tsx
  src/containers/detailPage/prodInfo/useProdInfo.ts
  src/elements/Buttons.tsx
  src/elements/Loading.tsx
  src/elements/SearchBar.tsx
  src/shared/apis/api.ts
  src/style/style.d.ts
  src/style/theme.ts
  tsconfig.json
Labels: task

#110 마이페이지 위시리스트 기능구현
  src/components/card/Card.tsx
  src/components/card/card.type.ts
  src/components/myPage/wishCard/WishCard.tsx
  src/components/myPage/wishCard/useWishCard.ts
  src/components/myPage/wishCard/wishCard.style.ts
  src/containers/listPage/listModa/ListModal.tsx
  src/containers/myPage/wish/Wish.tsx
  src/containers/myPage/wish/useWish.ts
  src/containers/myPage/wish/wish.type.ts
  src/shared/apis/instance.ts
Labels: task

#112 메인페이지 변수 수정
  src/components/mainPage/bestCards/BestCards.tsx
  src/components/mainPage/newCarousel/NewCarousel.tsx
Labels: task

#114 상세페이지 배포 테스트
  src/components/detailPage/history/History.tsx
  src/components/detailPage/prodCarousel/ProdCarousel.tsx
  src/components/detailPage/prodCarousel/prodCarousel.type.ts
  src/components/detailPage/prodImg/ProdImg.tsx
  src/components/detailPage/prodImg/prodImg.type.ts
  src/components/detailPage/prodOpt/ProdOpt.tsx
  src/containers/detailPage/prodInfo/ProdInfo.tsx
  src/containers/detailPage/prodInfo/useProdInfo.ts
  src/containers/listPage/listModa/ListModal.tsx
  src/shared/apis/api.ts
  src/shared/apis/instance.ts
Labels: task

#115 리스트 모달 기능 추가
  src/components/listPage/cardIcon/CardIcon.tsx
  src/components/listPage/cardIcon/cardIcon.type.ts
  src/components/listPage/cardIcon/useCardIcon.ts
  src/containers/completePage/completeBody/CompleteBody.tsx
  src/containers/completePage/completeBody/completeBody.type.ts
  src/containers/completePage/completeBody/useCompleteBody.ts
  src/containers/listPage/cardList/CardList.tsx
  src/containers/listPage/cardList/cardList.type.ts
  src/containers/listPage/cardList/useCardList.ts
  src/containers/listPage/listModa/ListModal.tsx
  src/containers/searchPage/searchBody/SearchBody.tsx
  src/containers/searchPage/searchBody/searchPage.type.ts
  src/pages/SearchPage.tsx
  src/shared/apis/api.ts
Labels: task

#117 상세페이지 위시 추가 및 업데이트 구현
  src/components/detailPage/prodBtns/ProdBtns.tsx
  src/components/detailPage/prodBtns/prodBtns.type.ts
  src/components/detailPage/prodBtns/useProdLike.ts
  src/components/detailPage/prodOpt/ProdOpt.tsx
  src/components/detailPage/prodOpt/prodOpt.style.ts
  src/components/detailPage/prodOpt/prodOpt.type.ts
  src/containers/detailPage/prodInfo/ProdInfo.tsx
  src/elements/Loading.tsx
  src/pages/DetailPage.tsx
Labels: task

#116 메인페이지 스타일 수정 및 링크 추가
  src/components/mainPage/bestCards/BestCards.tsx
  src/components/mainPage/newCarousel/NewCarousel.tsx
  src/containers/mainPage/jisok/Jisok.tsx
  src/containers/mainPage/jisok/jisok.style.ts
  src/containers/mainPage/mainBanner/MainBanner.tsx
  src/containers/mainPage/socialLinkList/SocialLinkList.tsx
Labels: task

#119 상세 페이지 결제 상품 리스트
  src/components/detailPage/prodBtns/ProdBtns.tsx
  src/components/detailPage/prodBtns/prodBtns.type.ts
  src/components/detailPage/prodOpt/ProdOpt.tsx
Labels: task
