Repository ad-earth/FE-client, pull requests merged in 2022-10, with the labels that each got.

#126 10/5 고정 이미지 s3 url 로 변경, cicd 배포 yml 코드 수정 Closes #58
  .github/workflows/main.yml
  src/components/detailPage/deliveryInfo/DeliveryInfo.tsx
  src/containers/mainPage/bestProd/BestProd.tsx
  src/containers/mainPage/mainBanner/MainBanner.tsx
  src/containers/mainPage/socialLinkList/SocialLinkList.tsx
  src/shared/utils/imgUrls.ts
Labels: task

#131 📝 feat. indexedDB 데이터 옵션별 주문 금액 추가
  src/components/detailPage/prodBtns/ProdBtns.tsx
Labels: attention!, task

#130 리뷰모달 , 리뷰 버튼 버그 수정
  src/components/modal/reviewModal/ReviewModal.tsx
  src/components/myPage/order/orderList/OrderList.tsx
  src/components/myPage/order/product/Product.tsx
  src/components/myPage/userHeadInfo/UserHeadInfo.tsx
  src/components/myPage/wishCard/WishCard.tsx
  src/containers/myPage/cancel/Cancel.tsx
  src/containers/myPage/cancel/cancel.type.ts
  src/containers/myPage/cancelDetail/CancelDetail.tsx
  src/containers/myPage/order/Order.tsx
  src/containers/myPage/order/order.type.ts
  src/containers/myPage/wish/Wish.tsx
Labels: bug

#148 10/23 상세페이지 상세 정보 및 구매평 구현
  package.json
  src/App.tsx
  src/components/detailPage/buttons/Buttons.tsx
  src/components/detailPage/buttons/useLikeQuery.ts
  src/components/detailPage/comment/Comment.tsx
  src/components/detailPage/comment/comment.style.ts
  src/components/detailPage/comment/comment.type.ts
  src/components/detailPage/comment/useDeleteCommentQuery.ts
  src/components/detailPage/commentList/CommentList.tsx
  src/components/detailPage/commentList/commentList.style.ts
  src/components/detailPage/commentList/commentList.type.ts
  src/components/detailPage/description/Description.tsx
  src/components/detailPage/description/description.style.ts
  src/components/detailPage/description/description.type.ts
  src/components/detailPage/navigation/Navigation.tsx
  src/components/detailPage/prodComments/ProdComments.tsx
  src/components/detailPage/prodComments/prodComments.style.ts
  src/components/detailPage/prodDetails/ProdDetails.tsx
  src/components/modal/optionModal/OptionModal.tsx
  src/components/modal/optionModal/useGetOption.ts
  src/containers/detailPage/contents/Contents.tsx
  src/containers/detailPage/contents/contents.style.ts
  src/containers/detailPage/contents/useContentsQuery.ts
  src/containers/detailPage/contents/useGetCommentsQuery.ts
  src/containers/detailPage/details/Details.tsx
  src/containers/detailPage/details/useDetailQuery.ts
  src/containers/detailPage/prodContents/ProdContents.tsx
  src/elements/Input.tsx
  src/pages/DetailPage.tsx
  src/shared/apis/api.ts
  yarn.lock
Labels: 상세페이지

#162 📝 feat. 서치바 라우팅 설정
  src/elements/SearchBar.tsx
Labels: 검색페이지

#163 10/24 구매평 수정
  src/containers/detailPage/contents/useGetCommentsQuery.ts
  src/containers/mainPage/mainList/MainList.tsx
Labels: bug, 상세페이지, 메인페이지

#168 10/25 전역 에러 UI 및 state 처리, custom hook 추가
  .vscode/settings.json
  src/App.tsx
  src/components/detailPage/buttons/Buttons.tsx
  src/components/detailPage/buttons/buttons.type.ts
  src/components/detailPage/commentList/CommentList.tsx
  src/components/detailPage/commentList/commentList.type.ts
  src/components/detailPage/description/description.style.ts
  src/components/detailPage/productCarousel/ProductCarousel.tsx
  src/components/detailPage/productCarousel/productCarousel.type.ts
  src/components/detailPage/productImgs/ProductImgs.tsx
  src/components/detailPage/productImgs/productImgs.type.ts
  src/components/detailPage/productName/ProductName.tsx
  src/components/detailPage/productName/productName.type.ts
  src/components/detailPage/productOptions/ProductOptions.tsx
  src/components/detailPage/productOptions/optionsHandler.ts
  src/components/detailPage/productOptions/productOptions.type.ts
  src/components/detailPage/productQty/ProductQty.tsx
  src/components/detailPage/productQty/productQty.type.ts
  src/components/detailPage/productSummary/ProductSummary.tsx
  src/components/detailPage/productSummary/productSummary.type.ts
  src/components/mainPage/bestCards/BestCards.tsx
  src/components/mainPage/newCarousel/NewCarousel.tsx
  src/containers/detailPage/contents/Contents.tsx
  src/containers/detailPage/details/Details.tsx
  src/containers/detailPage/details/useDetailQuery.ts
  src/containers/listPage/listModal/ListModal.tsx
  src/containers/mainPage/jisok/Jisok.tsx
  src/containers/mainPage/mainBanner/MainBanner.tsx
  src/elements/Buttons.tsx
  src/elements/Error.tsx
  src/hooks/useViewport.ts
  src/redux/reducer/detailSlice.ts
  src/redux/reducer/errorSlice.ts
  src/redux/reducer/optionSlice.ts
  src/redux/store.ts
Labels: refactoring, 상세페이지

#169 10/26 indexedDB 데이터 처리 및 상세페이지 디버깅
  .vscode/settings.json
  src/App.tsx
  src/components/detailPage/buttons/Buttons.tsx
  src/components/detailPage/buttons/buttons.type.ts
  src/components/detailPage/buttons/useLikeQuery.ts
  src/components/detailPage/commentList/CommentList.tsx
  src/components/detailPage/commentList/commentList.type.ts
  src/components/detailPage/description/Description.tsx
  src/components/detailPage/description/description.style.ts
  src/components/detailPage/description/description.type.ts
  src/components/detailPage/productCarousel/ProductCarousel.tsx
  src/components/detailPage/productCarousel/productCarousel.type.ts
  src/components/detailPage/productImgs/ProductImgs.tsx
  src/components/detailPage/productImgs/productImgs.type.ts
  src/components/detailPage/productName/ProductName.tsx
  src/components/detailPage/productName/productName.type.ts
  src/components/detailPage/productOptions/ProductOptions.tsx
  src/components/detailPage/productOptions/optionsHandler.ts
  src/components/detailPage/productOptions/productOptions.type.ts
  src/components/detailPage/productQty/ProductQty.tsx
  src/components/detailPage/productQty/productQty.type.ts
  src/components/detailPage/productSummary/ProductSummary.tsx
  src/components/detailPage/productSummary/productSummary.type.ts
  src/components/mainPage/bestCards/BestCards.tsx
  src/components/mainPage/newCarousel/NewCarousel.tsx
  src/containers/detailPage/contents/Contents.tsx
  src/containers/detailPage/contents/useContentsQuery.ts
  src/containers/detailPage/details/Details.tsx
  src/containers/detailPage/details/useDetailQuery.ts
  src/containers/listPage/listModal/ListModal.tsx
  src/containers/mainPage/jisok/Jisok.tsx
  src/containers/mainPage/mainBanner/MainBanner.tsx
  src/elements/Buttons.tsx
  src/elements/ChoiceModal.tsx
  src/elements/Error.tsx
  src/hooks/useAllCartDB.ts
  src/hooks/useAllPaymentDB.ts
  src/hooks/useCartDB.ts
  src/hooks/usePaymentDB.ts
  src/hooks/useViewport.ts
  src/redux/reducer/detailSlice.ts
  src/redux/reducer/errorSlice.ts
  src/redux/reducer/optionSlice.ts
  src/redux/store.ts
  src/shared/apis/api.ts
  src/shared/utils/delCartDB.ts
  src/shared/utils/delPaymentDB.ts
  src/shared/utils/putCartDB.ts
  src/shared/utils/putPaymentDB.ts
Labels: attention!, refactoring, task, 상세페이지

#171 10/27 refactoring & debug
  src/components/detailPage/buttons/Buttons.tsx
  src/components/detailPage/buttons/buttons.type.ts
  src/components/detailPage/buttons/useLikeQuery.ts
  src/components/detailPage/description/Description.tsx
  src/components/detailPage/description/description.type.ts
  src/components/detailPage/productQty/ProductQty.tsx
  src/containers/detailPage/contents/Contents.tsx
  src/containers/detailPage/contents/useContentsQuery.ts
  src/containers/detailPage/details/useDetailQuery.ts
  src/elements/ChoiceModal.tsx
  src/hooks/useAllCartDB.ts
  src/hooks/useAllPaymentDB.ts
  src/hooks/useCartDB.ts
  src/hooks/usePaymentDB.ts
  src/redux/reducer/detailSlice.ts
  src/shared/apis/api.ts
  src/shared/utils/delCartDB.ts
  src/shared/utils/delPaymentDB.ts
  src/shared/utils/putCartDB.ts
  src/shared/utils/putPaymentDB.ts
Labels: refactoring, 상세페이지, 메인페이지

#173 마이페이지 버그 수정 및 코드 추가
  src/App.tsx
  src/components/modal/reviewModal/ReviewModal.tsx
  src/components/modal/reviewModal/reviewModal.style.ts
  src/components/modal/reviewModal/reviewModal.type.ts
  src/components/modal/reviewModal/starRate/StarRate.tsx
  src/components/modal/reviewModal/starRate/starRate.style.ts
  src/components/modal/reviewModal/starRate/starRate.type.ts
  src/components/modal/reviewModal/useReviewModal.ts
  src/components/modal/reviewModal/useReviewModalQuery.ts
  src/components/myPage/asideNav/AsideNav.tsx
  src/components/myPage/asideNav/asideNav.style.ts
  src/components/myPage/order/orderAddress/OrderAddress.tsx
  src/components/myPage/order/orderAddress/orderAddress.type.ts
  src/components/myPage/order/orderList/OrderList.tsx
  src/components/myPage/order/orderList/orderList.type.ts
  src/components/myPage/order/orderListDetail/OrderListDetail.tsx
  src/components/myPage/order/orderListDetail/orderListDetail.type.ts
  src/components/myPage/order/orderNumber/OrderNumber.tsx
  src/components/myPage/order/orderNumber/orderNumber.type.ts
  src/components/myPage/userHeadInfo/UserHeadInfo.tsx
  src/components/myPage/userHeadInfo/userHeadInfo.style.ts
  src/containers/myPage/Aside.tsx
  src/containers/myPage/order/Order.tsx
  src/containers/myPage/order/useOrderQuery.ts
  src/containers/myPage/orderDetail/OrderDetail.tsx
  src/elements/buttons/Buttons.tsx
  src/elements/buttons/buttons.style.ts
  src/elements/buttons/buttons.type.ts
  src/pages/MyPage.tsx
  src/pages/NotFound.tsx
  src/redux/reducer/reviewSlice.ts
  src/redux/store.ts
Labels: bug, task, 마이페이지

#178 마이페이지 버그 수정
  src/components/modal/reviewModal/ReviewModal.tsx
  src/components/modal/reviewModal/reviewModal.type.ts
  src/components/modal/reviewModal/useReviewModalQuery.ts
  src/components/myPage/order/orderList/OrderList.tsx
  src/components/myPage/userHeadInfo/UserHeadInfo.tsx
  src/containers/myPage/cancel/cancel.type.ts
  src/containers/myPage/order/order.type.ts
Labels: bug
